version: '3.7'
services:
    mysql:
        image: mysql:5.7
        ports: ['3306:3306']
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: 'coffee_machine'
            MYSQL_DATABASE: 'coffee_machine'
            MYSQL_USER: 'coffee_machine'
            MYSQL_PASSWORD: 'coffee_machine'
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/images/mysql:/docker-entrypoint-initdb.d
    php:
        build: ./docker/images/php
        ports: ['9000:9000']
        volumes: ['./:/var/www/symfony:cached']
    nginx:
        build: ./docker/images/nginx
        ports: ['80:80']
        volumes: ['./:/var/www/symfony:cached']